name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # 当推送到 main 分支时自动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. 设置 QEMU (这是实现跨架构模拟编译的关键)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # 2. 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. 指定构建多平台
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # 在这里指定你需要支持的平台
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/yx-tools:latest
